package com.harmoniedev.api.audit.domain.enums;

public enum AuditAction {
	REGISTER,
	LOGIN,
	LOGIN_FAILED,
	LOGOUT,
	REFRESH,
	ADMIN_CREATE_USER,
	PASSWORD_RESET_REQUESTED,
	PASSWORD_RESET_COMPLETED,
	JOIN_REQUEST_SUBMITTED,
	JOIN_REQUEST_CONVERTED,
	ADMIN_UPDATE_USER,
	ADMIN_DELETE_USER,
	RENEWAL_REQUESTED,
	RENEWAL_APPROVED,
	RENEWAL_REJECTED
}
